Merge with jdk-17-ga.
Command: $ git merge --no-ff jdk-17-ga

Manual updates:

- Add `#include "memory/resourceArea.hpp"` in src/hotspot/share/tsan/tsanOopMap.cpp to resolve compiler error:

tsanOopMap.cpp:351:5: error: use of undeclared identifier 'ResourceMark'; did you mean 'ResourceStack'?
    ResourceMark rm;
    ^~~~~~~~~~~~
    ResourceStack

- Remove `AMD64_ONLY(assert((id_u8 & left_n_bits(17)) == 0, "jmethodID is not aligned");)` in classFileParser.cpp. `left_n_bits` has been removed by https://bugs.openjdk.org/browse/JDK-8178348

- Change `obj_field_addr_raw<oop>()` to `field_addr()` in java_lang_Class::init_lock_addr in javaClasses.cpp.

- Remove `ShenandoahTSANWeakRoot::ShenandoahTSANWeakRoot` as `ShenandoahWeakSerialRoot` is removed in shenandoahPhaseTimings.hpp.

- Remove JVMWrapper calls in tsan related functions in jvm.cpp. The macro has been removed.

- Change to use `current` for `JRT_ENTRY(void, SharedRuntime::tsan_interp_method_entry(JavaThread* thread))` as JRT_ENTRY macro expects `current`, sharedRuntime.cpp.

- Change `THREAD` to `current` in synchronizer.cpp.